server:
  port: 8086
  forward-headers-strategy: framework

spring:
  application:
    name: portfolio-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/Stock_Exchange_API

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: false   # 🚫 Disable UI in microservice

eureka:
  client:
    service-url:
        defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true

management:
  tracing:
    sampling:
      probability: 1.0   # start with 100%, reduce in prod
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId},spanId=%X{spanId}]"
